import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/noto-sans-arabic/arabic-400.css';
import '@fontsource/noto-sans-arabic/latin-400.css';
import './style.css';
import {brandLockup} from '../branding.js';
import {createClientDashboard} from '../portal/admin.js';
import {language as savedLanguage,setLanguage} from '../portal/api.js';
import {appRoot} from '../routes.js';
import {generate,loadPreview,renderPage,original,templateUrl} from '../pdf.js';
import {runtimeDocument} from './catalogue.js';
import {inspectPDF} from './importer.js';
import {layoutConflicts,assertLayout} from './layout.js';
const app=document.querySelector('#app'),e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let dashboard=null,managementSession=null,lang=savedLanguage(),activeView='overview';
const t=(en,ar)=>lang==='ar'?ar:en;
const canManageDocuments=()=>managementSession?.authenticated===true&&managementSession.role==='superadmin'&&managementSession.permissions?.manage_documents===true;
const canChangeAccountType=()=>managementSession?.authenticated===true&&managementSession.role==='superadmin'&&managementSession.permissions?.change_account_type===true;
let csrf='',state=null,dirty=false,editing=null,pageNumber=1,selected=null,pdf=null,drawType=null,serial=Date.now(),sampled=new Set(),renderEpoch=0;
const endpoint=action=>`${appRoot}api/management.php?action=${action}`;
async function api(action,body){
 if(!['session','login','logout'].includes(action)&&!canManageDocuments())throw Error(t('Document management is available to the superadmin only.','إدارة المستندات متاحة للمشرف الرئيسي فقط.'));
 const multipart=body instanceof FormData,response=await fetch(endpoint(action),{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'X-CSRF-Token':csrf,...(multipart?{}:{'Content-Type':'application/json'})}:{},body:body?(multipart?body:JSON.stringify(body)):undefined});
 const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error||t('Could not complete the request.','تعذّر إكمال الطلب.')),{status:response.status});return data;
}
function notice(message,error=false){const node=(error&&document.querySelector('.modal[open] [data-dialog-notice]'))||document.querySelector('#notice');if(!node)return;node.textContent=message;node.className=error?'error':'';node.scrollIntoView({block:'nearest'});}
function handleError(error){
 if(error.status===401&&managementSession?.authenticated){managementSession=null;state=null;editing=null;dirty=false;dashboard?.cancel();dashboard=null;showLogin();notice(t('Your management session expired. Please sign in again.','انتهت جلسة الإدارة. يرجى تسجيل الدخول مجددًا.'),true);return true;}
 if(error.status===403&&error.message==='Only the superadmin can manage documents.'){managementSession.permissions.manage_documents=false;state=null;editing=null;dirty=false;shell(`<main class="panel login"><h1>${t('Access changed','تغيّرت صلاحيات الحساب')}</h1><p>${t('Reload to refresh your management access.','أعد تحميل الصفحة لتحديث صلاحيات حساب الإدارة.')}</p></main>`,{view:'overview'});notice(error.message,true);return true;}
 return false;
}
function bind(selector,event,handler){document.querySelectorAll(selector).forEach(el=>el.addEventListener(event,async ev=>{try{await handler(ev,el);}catch(error){if(!handleError(error))notice(error.message,true);}}));}
function changed(){dirty=true;sampled.clear();const reviewButton=document.querySelector('#review-document');if(reviewButton)reviewButton.disabled=true;const sampleStatus=document.querySelector('#sample-status');if(sampleStatus)sampleStatus.textContent='Layout changed — regenerate both samples.';if(editing)editing.reviewed=false;document.querySelector('#draft-status').textContent='Unsaved changes';}
function shell(content,{view='documents'}={}){
 activeView=view;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
 const signedIn=managementSession?.authenticated===true,items=[['overview','Overview','نظرة عامة','data-overview id="client-dashboard"'],['reviews','Review forms','مراجعة النماذج','data-reviews'],['users','Clients','العملاء','data-users'],...(canManageDocuments()?[['documents','Documents','المستندات','data-documents']]:[])];
 app.innerHTML=`<header class="management-header" dir="${lang==='ar'?'rtl':'ltr'}"><div class="management-header-inner"><div class="management-brand">${brandLockup()}<small class="management-context" data-management-label>${t('MANAGEMENT','الإدارة')}</small></div><div class="management-controls">${signedIn?`<nav class="management-navigation" aria-label="${t('Management navigation','التنقل في الإدارة')}">${items.map(([id,en,ar,attrs])=>`<button type="button" data-management-view="${id}" ${attrs} ${view===id?'aria-current="page"':''}>${t(en,ar)}</button>`).join('')}</nav>`:''}<div class="management-account-actions"><button type="button" class="management-language" data-admin-language lang="${lang==='ar'?'en':'ar'}">${t('العربية','English')}</button>${signedIn?`<button type="button" id="logout">${t('Sign out','تسجيل الخروج')}</button>`:''}</div></div></div></header><div id="notice" role="status"></div>${content}`;
 bind('[data-management-view]','click',async(ev,button)=>{if(dirty)await saveDraft();if(button.dataset.managementView==='documents')await openDocuments();else await showDashboard(button.dataset.managementView);});
 bind('[data-admin-language]','click',async()=>{lang=lang==='ar'?'en':'ar';setLanguage(lang);if(!signedIn){showLogin();return;}if(activeView==='documents'){if(editing)await editor();else home();}else await dashboard.refresh();});
 bind('#logout','click',async()=>{if(dirty&&!confirm(t('Discard unsaved changes and sign out?','تجاهل التغييرات غير المحفوظة وتسجيل الخروج؟')))return;await api('logout',{});dirty=false;location.reload();});
}
function showLogin(){shell(`<main class="panel login"><h1>${t('Management sign in','تسجيل دخول الإدارة')}</h1><p class="muted">${t('Sign in with your management username and password.','أدخل اسم المستخدم وكلمة المرور لحساب الإدارة.')}</p><form id="login"><label>${t('Username','اسم المستخدم')}<input id="username" name="username" autocomplete="username" autocapitalize="none" spellcheck="false" maxlength="80" dir="ltr" required></label><label>${t('Password','كلمة المرور')}<input id="password" name="password" type="password" autocomplete="current-password" dir="ltr" required></label><div class="actions" style="margin-top:20px"><button class="primary">${t('Sign in','تسجيل الدخول')}</button></div></form></main>`,{view:'overview'});
 bind('#login','submit',async ev=>{ev.preventDefault();const button=ev.target.querySelector('button');button.disabled=true;try{const freshSession=await api('session');csrf=freshSession.csrf;const response=await api('login',{username:document.querySelector('#username').value,password:document.querySelector('#password').value});csrf=response.csrf;managementSession=response;await showDashboard();}finally{if(button.isConnected)button.disabled=false;}});
}
async function start(){managementSession=await api('session');csrf=managementSession.csrf;if(!managementSession.configured){shell(`<main class="panel login"><h1>${t('Management setup','إعداد الإدارة')}</h1><p>${t('Management access has not been configured.','لم يتم إعداد حساب الإدارة بعد.')}</p></main>`,{view:'overview'});return;}if(managementSession.authenticated){await showDashboard();return;}showLogin();}
async function showDashboard(view='overview'){dashboard??=createClientDashboard({shell,token:()=>csrf,language:()=>lang,canChangeAccountType,onError:handleError});await dashboard[view]();}
async function openDocuments(){if(!canManageDocuments())return;dashboard?.cancel();if(!state)state=await api('state');home();}
function toolbar(title,buttons=''){return `<div class="toolbar"><div><h1>${title}</h1><div class="status-strip"><span id="draft-status">${dirty?'Unsaved changes':'Draft saved'}</span><span>Revision ${state.revision}</span></div></div><div class="actions">${buttons}</div></div>`;}
async function saveDraft(){state=await api('save',{revision:state.revision,draft:state.draft});dirty=false;if(editing)editing=state.draft.documents.find(d=>d.id===editing.id);return state;}
function home(){if(!canManageDocuments()||!state)return;editing=null;selected=null;shell(`<main class="shell">${toolbar('Your document catalogue','<button id="restore">Restore previous publication</button><button id="save">Save draft</button><button id="publish" class="primary">Publish catalogue</button>')}<p class="muted">Draft edits stay private until you publish. Existing form fields and saved customer answers stay unchanged.</p><div class="actions" style="margin:20px 0"><button id="upload" class="primary">＋ Add document</button><a class="link-button" href="${appRoot}individuals/" target="_blank" rel="noopener">Preview individuals ↗</a><a class="link-button" href="${appRoot}companies/" target="_blank" rel="noopener">Preview companies ↗</a></div><div class="columns">${['individual','corporate'].map(group=>`<section class="panel"><h2>${group==='individual'?'Individuals':'Companies'}</h2>${state.draft.orders[group].map((id,i)=>{const d=state.draft.documents.find(d=>d.id===id);return `<div class="document-row" data-document="${id}"><span class="number">${i+1}</span><div class="info"><strong>${e(d.title)}</strong><small class="rtl">${e(d.ar)}</small><small>${d.group==='shared'?'<span class="badge">Shared document</span> · ':''}${d.pages} pages · ${d.downloadOnly?'Download only':d.builtin?'Existing form':d.reviewed?'Reviewed':'Review needed'}</small></div><div class="actions"><button class="small" aria-label="Move document ${i+1} up in ${group}" data-move="${id}" data-group="${group}" data-delta="-1" ${i===0?'disabled':''}>↑</button><button class="small" aria-label="Move document ${i+1} down in ${group}" data-move="${id}" data-group="${group}" data-delta="1" ${i===state.draft.orders[group].length-1?'disabled':''}>↓</button><button class="small" data-edit="${id}">Edit</button></div></div>`;}).join('')}</section>`).join('')}</div></main>`);
 bind('#save','click',async()=>{await saveDraft();home();notice('Draft saved. The published catalogue has not changed.');});
 bind('#publish','click',async()=>{if(!confirm('Publish this draft catalogue to this installation?'))return;if(dirty)await saveDraft();state=await api('publish',{revision:state.revision});home();notice('Catalogue published.');});
 bind('#restore','click',async()=>{if(!confirm('Replace the draft with the previous published catalogue?'))return;state=await api('restore',{revision:state.revision});dirty=false;home();notice('Previous catalogue restored to the draft. Publish when ready.');});
 bind('[data-move]','click',(ev,button)=>{const order=state.draft.orders[button.dataset.group],i=order.indexOf(button.dataset.move),j=i+Number(button.dataset.delta);[order[i],order[j]]=[order[j],order[i]];changed();home();});
 bind('[data-edit]','click',(ev,button)=>metadataModal(state.draft.documents.find(d=>d.id===button.dataset.edit)));
 bind('#upload','click',()=>uploadModal());
}
function modal(html){
 const trigger=document.activeElement,wrap=document.createElement('dialog');wrap.className='modal';wrap.innerHTML=html+'<p data-dialog-notice role="status" aria-live="polite"></p>';
 wrap.querySelector('h2')?.setAttribute('id','management-dialog-title');wrap.setAttribute('aria-labelledby','management-dialog-title');app.append(wrap);
 wrap.addEventListener('close',()=>{wrap.remove();if(trigger?.isConnected)trigger.focus();});
 wrap.addEventListener('cancel',ev=>{if(wrap.getAttribute('aria-busy')==='true')ev.preventDefault();});
 wrap.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>wrap.close());wrap.showModal();return wrap;
}
function metaFields(d){return `<div class="field-grid"><label>English title<input name="title" value="${e(d.title)}" required maxlength="1000"></label><label>العنوان بالعربية<input class="rtl" name="ar" value="${e(d.ar)}" required maxlength="1000"></label><label>English description<textarea name="description">${e(d.description)}</textarea></label><label>الوصف بالعربية<textarea class="rtl" name="arDescription">${e(d.arDescription)}</textarea></label></div>${!d.builtin?`<label>Audience<select name="group">${[['individual','Individuals'],['corporate','Companies'],['shared','Both · shared document']].map(([v,l])=>`<option value="${v}" ${d.group===v?'selected':''}>${l}</option>`).join('')}</select></label><label style="margin-top:16px"><input type="checkbox" name="downloadOnly" ${d.downloadOnly?'checked':''}> Download only (no online fields)</label>`:''}`;}
function formMeta(form){const fd=new FormData(form);return {title:String(fd.get('title')||'').trim(),ar:String(fd.get('ar')||'').trim(),description:String(fd.get('description')||''),arDescription:String(fd.get('arDescription')||''),...(fd.has('group')?{group:fd.get('group'),downloadOnly:fd.has('downloadOnly')}:{})};}
function syncOrders(){for(const group of ['individual','corporate']){const ids=state.draft.documents.filter(d=>d.group===group||d.group==='shared').map(d=>d.id);state.draft.orders[group]=[...state.draft.orders[group].filter(id=>ids.includes(id)),...ids.filter(id=>!state.draft.orders[group].includes(id))];}}
function metadataModal(d){const wrap=modal(`<h2>Edit document</h2><form id="metadata">${metaFields(d)}<div class="actions">${!d.builtin?'<button type="button" class="danger" id="remove-document">Remove from draft</button>':''}<button type="button" data-close>Cancel</button>${!d.builtin?'<button type="submit" name="mode" value="fields">Edit fields</button>':''}<button type="submit" name="mode" value="save" class="primary">Apply to draft</button></div></form>`);
 bind('#metadata','submit',async ev=>{ev.preventDefault();Object.assign(d,formMeta(ev.target));syncOrders();changed();wrap.remove();if(ev.submitter?.value==='fields'){await saveDraft();await openEditor(d.id);}else home();});
 bind('#remove-document','click',async()=>{if(!confirm('Remove this uploaded document from the draft? Its published version stays until the next publication.'))return;if(dirty)await saveDraft();state=await api('remove',{revision:state.revision,id:d.id});wrap.remove();home();});
}
function uploadModal(){const wrap=modal(`<h2>Add a document</h2><p class="muted">Upload a blank PDF. Existing fields import automatically; printed blank lines become suggestions. Review placement and both languages before publishing.</p><form id="new-document"><label>PDF (up to 20 MB, 50 pages)<input type="file" name="pdf" accept="application/pdf" required></label><div style="margin-top:20px">${metaFields({group:'individual'})}</div><p id="upload-progress" role="status"></p><div class="actions"><button type="button" data-close>Cancel</button><button class="primary" id="upload-submit">Upload & prepare fields</button></div></form>`);
 bind('#new-document','submit',async ev=>{ev.preventDefault();const button=document.querySelector('#upload-submit');button.disabled=true;wrap.setAttribute('aria-busy','true');wrap.querySelector('[data-close]').disabled=true;try{const file=ev.target.elements.pdf.files[0],meta=formMeta(ev.target),result=await inspectPDF(file,message=>document.querySelector('#upload-progress').textContent=message);if(dirty)await saveDraft();const payload=new FormData();payload.set('pdf',file);payload.set('revision',state.revision);payload.set('metadata',JSON.stringify({...result,...meta}));state=await api('upload',payload);dirty=false;const d=state.draft.documents.at(-1);wrap.remove();await openEditor(d.id);notice(`${result.detected} fields prepared${result.suggested?` (${result.suggested} suggestions)`:''}. Check the labels and placement before publishing.`);}finally{button.disabled=false;wrap.removeAttribute('aria-busy');wrap.querySelector('[data-close]').disabled=false;}});
}
async function openEditor(id){editing=state.draft.documents.find(d=>d.id===id);pageNumber=1;selected=null;sampled.clear();pdf=await loadPreview(await original(runtimeDocument(editing)));await editor();}
function allFields(){return [...editing.fields,...editing.signatures.map(f=>({...f,type:'signature'}))];}
function getSelected(){return editing.fields.find(f=>f.id===selected)||editing.signatures.find(f=>f.id===selected);}
function selectedIsSignature(){return editing.signatures.some(f=>f.id===selected);}
function editorMarkup(){return `<main class="shell">${toolbar(e(editing.title),'<button id="back">← Catalogue</button><button id="save-editor" class="primary">Save draft</button>')}<div class="editor"><aside class="panel editor-sidebar"><h2>Fields & placement</h2><p class="note">${editing.importedWidgets?'Imported fields still need a page-by-page check.':'This PDF has no existing fields. Suggestions are incomplete: add missing fields and remove incorrect suggestions before publishing.'}</p><p class="danger">${layoutConflicts(editing).length?'Overlapping answer areas found. Move or resize them before review.':''}</p><p class="muted">Choose a field, or draw a new box on the original page. Drag a box to move it; drag its bottom corner to resize.</p><div class="actions"><button class="small" data-draw="text">＋ Text</button><button class="small" data-draw="choice">＋ Checkbox</button><button class="small" data-draw="signature">＋ Signature</button></div><div class="field-list">${allFields().map((f,i)=>`<button data-select="${f.id}" class="${selected===f.id?'active':''}">${i+1}. ${e(f.label||f.ar||'Unlabelled field')} · p${f.page}</button>`).join('')}</div><div id="field-properties"></div><div class="editor-actions"><h3>Check the filled PDF</h3><p class="muted">Generate both samples and inspect every page before marking this form reviewed.</p><div class="actions"><button class="small" data-sample="en">English sample</button><button class="small" data-sample="ar">Arabic sample</button></div><p id="sample-status">${[...sampled].map(x=>x==='en'?'English generated':'Arabic generated').join(' · ')}</p><label><input type="checkbox" id="review-confirm"> I checked every printed field is included and both samples have no overlaps.</label><button class="primary" id="review-document" ${sampled.size<2||layoutConflicts(editing).length?'disabled':''}>Mark reviewed</button><p class="muted">${editing.reviewed?'Reviewed. Ready to publish.':'Review needed before publication.'}</p></div></aside><section class="panel"><div class="toolbar"><div class="actions"><button id="previous" ${pageNumber===1?'disabled':''}>←</button><b>Page ${pageNumber} / ${editing.pages}</b><button id="next" ${pageNumber===editing.pages?'disabled':''}>→</button></div><span id="drawing-status" class="muted">${drawType?'Draw a '+drawType+' box':''}</span></div><div id="paper" class="paper ${drawType?'drawing':''}" style="aspect-ratio:${editing.pageSizes[pageNumber-1][0]}/${editing.pageSizes[pageNumber-1][1]}"><canvas id="page"></canvas><div id="boxes"></div></div></section></div></main>`;}
async function editor(){shell(editorMarkup());properties();boxes();const epoch=++renderEpoch;await renderPage(pdf,pageNumber,document.querySelector('#page'),800);if(epoch!==renderEpoch)return;
 bind('#back','click',async()=>{if(dirty)await saveDraft();await pdf.loadingTask.destroy();pdf=null;home();});
 bind('#save-editor','click',async()=>{await saveDraft();await editor();notice('Field layout saved to the draft.');});
 bind('#previous,#next','click',async(ev,el)=>{pageNumber+=el.id==='next'?1:-1;selected=null;await editor();});
 bind('[data-select]','click',async(ev,el)=>{selected=el.dataset.select;const f=getSelected();if(f.page!==pageNumber){pageNumber=f.page;await editor();}else{properties();boxes();}});
 bind('[data-draw]','click',(ev,el)=>{drawType=el.dataset.draw;document.querySelector('#paper').classList.add('drawing');document.querySelector('#drawing-status').textContent='Draw a '+drawType+' box on the page.';});
 bind('[data-sample]','click',async(ev,el)=>{await sample(el.dataset.sample);});
 bind('#review-document','click',async()=>{if(!document.querySelector('#review-confirm').checked)throw Error('Confirm that you checked all fields and both samples.');if(sampled.size<2)throw Error('Generate both samples first.');assertLayout(editing);await saveDraft();state=await api('review',{revision:state.revision,id:editing.id});editing=state.draft.documents.find(d=>d.id===editing.id);await editor();notice('Document reviewed. Return to the catalogue to publish.');});
 document.querySelector('#paper').addEventListener('pointerdown',startDrag);
}
const sharedCommon=['full_name','full_address','phone','mobile','email','client_number','account_number','building','street','district','city','postal','additional','country'];
function properties(){const root=document.querySelector('#field-properties'),f=getSelected();if(!f){root.innerHTML='<p class="note">Select a field to edit its English and Arabic labels and answer area.</p>';return;}const signature=selectedIsSignature();root.innerHTML=`<h3>Selected field</h3><label>English label<input data-prop="label" value="${e(f.label)}"></label><label>التسمية بالعربية<input class="rtl" data-prop="ar" value="${e(f.ar)}"></label>${!signature?`<label>Field type<select data-prop="type">${['text','email','tel','date','choice','select'].map(t=>`<option ${f.type===t?'selected':''}>${t}</option>`).join('')}</select></label>`:''}${f.type==='choice'?`<label><input type="checkbox" data-prop="multiple" ${f.multiple?'checked':''}> Allow multiple selections</label><p class="muted">Each option has its own box. Draw another checkbox to add an option.</p>${f.options.map((o,i)=>`<div class="option-row"><input aria-label="Option ${i+1} English" data-option="${i}" data-key="label" value="${e(o.label)}"><input aria-label="Option ${i+1} Arabic" class="rtl" data-option="${i}" data-key="ar" value="${e(o.ar)}"><button data-delete-option="${i}" class="danger" aria-label="Delete option ${i+1}">×</button></div>`).join('')}`:f.type==='select'?`<label>Dropdown options (value | English | Arabic per line)<textarea id="select-options">${e((f.selectOptions||[]).map(o=>o.join(' | ')).join('\n'))}</textarea></label>`:''}${!signature&&f.type!=='choice'?`<div class="field-grid"><label>Text direction<select data-prop="direction">${['auto','ltr','rtl'].map(t=>`<option ${f.direction===t?'selected':''}>${t}</option>`).join('')}</select></label><label>Font size<input data-prop="fontSize" type="number" min="5" max="18" step=".5" value="${f.fontSize||10}"></label></div><label><input type="checkbox" data-prop="multiline" ${f.multiline?'checked':''}> Multiple lines</label>${['individual','corporate'].filter(g=>editing.group==='shared'||editing.group===g).map(g=>`<label>Copy shared ${g==='individual'?'individual':'company'} field<select data-shared="${g}"><option value="">No automatic copying</option>${[...sharedCommon,...(g==='individual'?['full_name_en','full_name_ar','en_first','en_middle','en_last','ar_first','ar_middle','ar_last','dob','id_number']:['company_name','inc_country','auth_name','auth_id'])].map(key=>`<option value="${key}" ${f.shared?.[g]===key?'selected':''}>${key.replaceAll('_',' ')}</option>`).join('')}</select></label>`).join('')}`:''}${f.rect?`<div class="field-grid">${['Left','Top','Width','Height'].map((label,i)=>`<label>${label} (pt)<input data-rect="${i}" type="number" step=".5" value="${Math.round(f.rect[i]*10)/10}"></label>`).join('')}</div>`:''}<button id="delete-field" class="danger small">Delete field</button>`;
 bind('[data-prop]','change',(ev,el)=>{const key=el.dataset.prop;let value=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(key==='type'&&value!==f.type){if(value==='choice'){f.options=[{value:'yes',label:'',ar:'',rect:f.rect||[30,30,12,12]}];f.rect=null;}else if(f.type==='choice'){f.rect=f.options[0]?.rect||[30,30,120,18];delete f.options;}if(value==='select')f.selectOptions=[['option_1','','']];}f[key]=value;changed();properties();boxes();});
 bind('[data-option]','input',(ev,el)=>{f.options[Number(el.dataset.option)][el.dataset.key]=el.value;changed();});
 bind('[data-delete-option]','click',(ev,el)=>{if(f.options.length===1)throw Error('Delete the field to remove its last option.');f.options.splice(Number(el.dataset.deleteOption),1);changed();properties();boxes();});
 bind('#select-options','change',(ev,el)=>{f.selectOptions=el.value.split('\n').filter(Boolean).map((line,i)=>{const a=line.split('|').map(x=>x.trim());return[a[0]||'option_'+i,a[1]||'',a[2]||''];});changed();});
 bind('[data-shared]','change',(ev,el)=>{f.shared??={};f.shared[el.dataset.shared]=el.value;changed();});
 bind('[data-rect]','change',(ev,el)=>{const old=f.rect.slice();f.rect[Number(el.dataset.rect)]=Number(el.value);const [w,h]=editing.pageSizes[f.page-1];if(f.rect[0]<0||f.rect[1]<0||f.rect[2]<2||f.rect[3]<2||f.rect[0]+f.rect[2]>w||f.rect[1]+f.rect[3]>h){f.rect=old;throw Error('Keep the field within the page.');}changed();boxes();});
 bind('#delete-field','click',async()=>{editing.fields=editing.fields.filter(x=>x.id!==selected);editing.signatures=editing.signatures.filter(x=>x.id!==selected);selected=null;changed();await editor();});
 document.querySelectorAll('[data-select]').forEach(b=>b.classList.toggle('active',b.dataset.select===selected));
}
function boxList(){return allFields().filter(f=>f.page===pageNumber).flatMap(f=>f.type==='choice'?f.options.map((o,i)=>({id:f.id,rect:o.rect,option:i})): [{id:f.id,rect:f.rect,option:-1}]);}
function boxes(){const [w,h]=editing.pageSizes[pageNumber-1],conflicts=new Set(layoutConflicts(editing).flatMap(c=>[c.first,c.second]));document.querySelector('#boxes').innerHTML=boxList().map((b,i)=>`<div class="box ${b.id===selected?'active':''} ${conflicts.has(b.id)?'conflict':''}" data-box="${b.id}" data-option-index="${b.option}" style="left:${b.rect[0]/w*100}%;top:${b.rect[1]/h*100}%;width:${b.rect[2]/w*100}%;height:${b.rect[3]/h*100}%"><span class="tag">${i+1}</span>${b.id===selected?'<span class="resize"></span>':''}</div>`).join('');}
function startDrag(event){if(event.button!==0)return;const paper=document.querySelector('#paper'),bounds=paper.getBoundingClientRect(),[w,h]=editing.pageSizes[pageNumber-1],point=ev=>[Math.max(0,Math.min(w,(ev.clientX-bounds.left)/bounds.width*w)),Math.max(0,Math.min(h,(ev.clientY-bounds.top)/bounds.height*h))],start=point(event),box=event.target.closest('[data-box]');if(!drawType&&!box)return;event.preventDefault();paper.setPointerCapture(event.pointerId);const creating=drawType;let f,rect,initial,resize=event.target.classList.contains('resize');
 if(box&&!creating){selected=box.dataset.box;f=getSelected();rect=f.type==='choice'?f.options[Number(box.dataset.optionIndex)].rect:f.rect;initial=rect.slice();properties();boxes();}
 const move=ev=>{const p=point(ev);if(creating){document.querySelector('#drawing-status').textContent=`New ${creating}: ${Math.round(Math.abs(p[0]-start[0]))} × ${Math.round(Math.abs(p[1]-start[1]))} pt`;return;}if(resize){rect[2]=Math.max(2,Math.min(w-initial[0],initial[2]+p[0]-start[0]));rect[3]=Math.max(2,Math.min(h-initial[1],initial[3]+p[1]-start[1]));}else{rect[0]=Math.max(0,Math.min(w-rect[2],initial[0]+p[0]-start[0]));rect[1]=Math.max(0,Math.min(h-rect[3],initial[1]+p[1]-start[1]));}boxes();};
 const stop=async ev=>{paper.removeEventListener('pointermove',move);paper.removeEventListener('pointerup',stop);paper.removeEventListener('pointercancel',stop);if(creating){const p=point(ev),r=[Math.min(start[0],p[0]),Math.min(start[1],p[1]),Math.abs(p[0]-start[0]),Math.abs(p[1]-start[1])];drawType=null;if(r[2]>=2&&r[3]>=2){const old=getSelected();if(creating==='choice'&&old?.type==='choice'&&old.page===pageNumber){old.options.push({value:'option_'+(++serial),label:'',ar:'',rect:r});}else{const field={id:'field_'+(++serial),label:'',ar:'',page:pageNumber,rect:r};if(creating==='signature')editing.signatures.push(field);else editing.fields.push({...field,type:creating,fontSize:10,direction:'auto',...(creating==='choice'?{rect:null,options:[{value:'yes',label:'',ar:'',rect:r}]}:{})});selected=field.id;}}}changed();await editor();};
 paper.addEventListener('pointermove',move);paper.addEventListener('pointerup',stop);paper.addEventListener('pointercancel',stop);
}
async function sample(lang){if(dirty)await saveDraft();const values={};for(const f of editing.fields){if(f.type==='choice')values[f.id]=f.multiple?f.options.map(o=>o.value):f.options[0]?.value;else if(f.type==='select')values[f.id]=f.selectOptions[0]?.[0]||'';else if(f.type==='date')values[f.id]='2026-09-17';else if(f.type==='email')values[f.id]='test@example.com';else if(f.type==='tel')values[f.id]='+966551234567';else values[f.id]=lang==='ar'?'أحمد علي':'Ahmad Ali';}
 const signatures={};if(editing.signatures.length){const canvas=document.createElement('canvas');canvas.width=280;canvas.height=90;const ctx=canvas.getContext('2d');ctx.strokeStyle='#1456a0';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(15,65);ctx.bezierCurveTo(45,5,45,80,80,35);ctx.bezierCurveTo(100,5,85,80,150,30);ctx.bezierCurveTo(165,65,195,20,255,40);ctx.stroke();for(const s of editing.signatures)signatures[s.id]=canvas.toDataURL('image/png');}const bytes=await generate(runtimeDocument(editing),values,signatures),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=`${editing.id}-${lang}-sample.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);sampled.add(lang);document.querySelector('#sample-status').textContent=[...sampled].map(x=>x==='en'?'English generated':'Arabic generated').join(' · ');document.querySelector('#review-document').disabled=sampled.size<2;notice('Sample downloaded. Check every page before marking this form reviewed.');}
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
start().catch(error=>{if(handleError(error))return;shell(`<main class="panel login"><h1>${t('Management unavailable','الإدارة غير متاحة')}</h1><p>${t('Please reload this page to try again.','أعد تحميل الصفحة للمحاولة مجددًا.')}</p></main>`,{view:'overview'});notice(error.message,true);});
