import {api,endpoint,e,errorText,when,language,setLanguage} from './api.js';
import {previewSubmission} from './preview.js';
import './admin.css';
export function createClientDashboard({shell,token,documents}){
 let lang=language(),view='overview',client=null,clientSubmissions=[],page=1,query='';
 const t=(en,ar)=>lang==='ar'?ar:en,request=(action,params={})=>api('admin_'+action,undefined,{params});
 function display(content){
  shell(`<main class="client-management" dir="${lang==='ar'?'rtl':'ltr'}"><div class="client-management-nav"><div><button data-overview class="${view==='overview'?'selected':''}">${t('Overview','نظرة عامة')}</button><button data-users class="${view==='users'||view==='client'?'selected':''}">${t('Clients','العملاء')}</button><button data-documents>${t('Documents','المستندات')}</button></div><button data-admin-language>${t('العربية','English')}</button></div>${content}</main>`);
  const header=document.querySelector('header');header.dir=lang==='ar'?'rtl':'ltr';header.querySelector('b').textContent=t('ITQAN CAPITAL','إتقان كابيتال');header.querySelector('span').textContent=t('CLIENT & DOCUMENT MANAGEMENT · TEST BRANCH','إدارة العملاء والمستندات · نسخة تجريبية');header.querySelector('#client-dashboard').textContent=t('Dashboard','لوحة التحكم');header.querySelector('#logout').textContent=t('Sign out','تسجيل الخروج');
  bind('[data-overview]',()=>overview());bind('[data-users]',()=>users());bind('[data-documents]',()=>documents());
  bind('[data-admin-language]',()=>{lang=lang==='ar'?'en':'ar';setLanguage(lang);return view==='overview'?overview():view==='client'?profile(client):users();});
 }
 function bind(selector,handler){document.querySelectorAll(selector).forEach(b=>b.onclick=async()=>{try{await handler(b);}catch(err){const n=document.querySelector('#notice');n.textContent=errorText(err,lang);n.className='error';}});}
 function subtitle(){return `<p class="client-muted">${t('All timestamps are shown in Riyadh time. Counts include submitted PDFs, not unfinished browser drafts.','جميع الأوقات بتوقيت الرياض. الإحصاءات تشمل ملفات PDF المرسلة، ولا تشمل المسودات غير المرسلة.')}</p>`;}
 function table(rows,{showClient=true}={}){return rows.length?`<div class="admin-table-wrap"><table class="admin-table"><thead><tr>${showClient?`<th>${t('Client','العميل')}</th>`:''}<th>${t('Document','المستند')}</th><th>${t('Submitted','تاريخ الإرسال')}</th><th>${t('Actions','الإجراءات')}</th></tr></thead><tbody>${rows.map(s=>`<tr>${showClient?`<td><button class="client-text-button" data-client="${s.user_id}">${e(s.name)}</button><small dir="ltr">${e(s.phone)}</small></td>`:''}<td><strong>${e(t(s.title,s.ar))}</strong><small>${t(s.audience==='individual'?'Individual':'Company',s.audience==='individual'?'فرد':'شركة')} · ${s.id.slice(0,8).toUpperCase()}</small><small class="version-badge">${t('Version','النسخة')} ${s.version} · ${s.archived_at?t('Archived','مؤرشفة'):t('Current','الحالية')}${s.restored_from?' · '+t('Restored','مستعادة'):''}</small></td><td class="admin-date">${e(when(s.created_at,lang))}${s.archived_at?`<small>${t('Archived','أُرشفت')} ${e(when(s.archived_at,lang))}</small>`:''}</td><td><div class="admin-row-actions"><button data-preview="${s.id}">${t('Preview & details','معاينة وتفاصيل')}</button><a href="${endpoint('admin_pdf',{id:s.id})}">${t('Download','تنزيل')}</a>${!showClient&&s.archived_at?`<button class="restore-version" data-restore="${s.id}">${t('Restore this version','استعادة هذه النسخة')}</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`:`<div class="admin-empty">${t('No forms have been submitted yet.','لم يتم إرسال أي نماذج بعد.')}</div>`;}
 function bindRows(){bind('[data-client]',b=>profile(b.dataset.client));bind('[data-preview]',b=>previewSubmission(b.dataset.preview,{admin:true,lang}));bind('[data-restore]',b=>restore(clientSubmissions.find(s=>s.id===b.dataset.restore)));}
 async function overview(){view='overview';const data=await request('dashboard');
  const categories=data.categories;
  display(`<div class="admin-heading"><div><span class="admin-eyebrow">${t('CLIENT MANAGEMENT','إدارة العملاء')}</span><h1>${t('Your submission dashboard','لوحة النماذج المرسلة')}</h1><p class="client-muted">${t('A clear view of your clients and the documents they send.','نظرة واضحة على عملائك والمستندات التي يرسلونها.')}</p></div><button data-refresh>${t('Refresh','تحديث')}</button></div><div class="admin-stats"><article><span>${t('Registered clients','العملاء المسجلون')}</span><strong>${data.stats.users}</strong><small>${t('All client accounts','جميع حسابات العملاء')}</small></article><article><span>${t('Clients who submitted','عملاء أرسلوا نماذج')}</span><strong>${data.stats.submitted_users}</strong><small>${t('Unique clients with at least one form','عملاء لديهم نموذج مرسل واحد على الأقل')}</small></article><article><span>${t('Current forms','النماذج الحالية')}</span><strong>${data.stats.active_submissions}</strong><small>${data.stats.submissions-data.stats.active_submissions} ${t('archived versions','نسخ مؤرشفة')} · ${data.stats.submissions} ${t('total submissions','إجمالي الإرسالات')}</small></article></div><section class="admin-card"><div class="admin-section-heading"><h2>${t('Forms by category','النماذج حسب الفئة')}</h2></div><div class="category-stats">${categories.map(d=>{const counts=data.counts.filter(c=>c.doc_id===d.id),count=counts.reduce((s,c)=>s+c.active_count,0);return `<article><span class="category-count">${count}</span><div><b>${e(t(d.title,d.ar))}</b><small>${d.group==='shared'?t('Individuals & companies','الأفراد والشركات'):t(d.group==='individual'?'Individuals':'Companies',d.group==='individual'?'الأفراد':'الشركات')}</small></div></article>`;}).join('')}</div></section><section class="admin-card"><div class="admin-section-heading"><h2>${t('Latest submissions','أحدث النماذج المرسلة')}</h2><button data-users>${t('View clients','عرض العملاء')}</button></div>${table(data.recent)}</section>${subtitle()}`);
  bind('[data-refresh]',overview);bindRows();
 }
 async function users(){view='users';const data=await request('users',{q:query,page});
  display(`<div class="admin-heading"><div><span class="admin-eyebrow">${t('CLIENT DIRECTORY','دليل العملاء')}</span><h1>${t('Clients','العملاء')}</h1><p class="client-muted">${data.total} ${t('registered accounts','حسابات مسجلة')}</p></div></div><form class="admin-search" id="client-search"><input name="q" value="${e(query)}" placeholder="${t('Search name, phone or email','ابحث بالاسم أو الجوال أو البريد')}" aria-label="${t('Search clients','بحث العملاء')}"><button class="primary">${t('Search','بحث')}</button></form><section class="admin-card"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>${t('Name','الاسم')}</th><th>${t('Contact','التواصل')}</th><th>${t('Registered','تاريخ التسجيل')}</th><th>${t('Forms','النماذج')}</th><th></th></tr></thead><tbody>${data.users.map(u=>`<tr><td><strong>${e(u.name)}</strong>${u.reset_required?`<small class="reset-badge">${t('Password change pending','بانتظار تغيير كلمة المرور')}</small>`:''}</td><td><bdi>${e(u.phone)}</bdi><small dir="ltr">${e(u.email||'—')}</small></td><td class="admin-date">${e(when(u.created_at,lang))}</td><td><span class="client-count">${u.active_submissions}</span><small>${u.submissions-u.active_submissions} ${t('archived','مؤرشفة')}</small></td><td><button data-client="${u.id}">${t('View profile','عرض الملف')}</button></td></tr>`).join('')}</tbody></table></div>${!data.users.length?`<div class="admin-empty">${t('No clients found.','لم يتم العثور على عملاء.')}</div>`:''}</section><div class="admin-pagination"><button data-prev ${page===1?'disabled':''}>${t('Previous','السابق')}</button><span>${page} / ${Math.max(1,Math.ceil(data.total/30))}</span><button data-next ${page*30>=data.total?'disabled':''}>${t('Next','التالي')}</button></div>`);
  document.querySelector('#client-search').onsubmit=ev=>{ev.preventDefault();query=new FormData(ev.target).get('q');page=1;users().catch(err=>{document.querySelector('#notice').textContent=errorText(err,lang);});};
  bind('[data-prev]',()=>{page--;return users();});bind('[data-next]',()=>{page++;return users();});bindRows();
 }
 async function profile(id){view='client';client=id;const {user,submissions}=await request('client',{id});clientSubmissions=submissions;const current=submissions.filter(s=>!s.archived_at),archived=submissions.filter(s=>s.archived_at);
  display(`<button class="client-text-button" data-users>${t('← All clients','جميع العملاء ←')}</button><div class="admin-heading"><div><span class="admin-eyebrow">${t('CLIENT PROFILE','ملف العميل')}</span><h1>${e(user.name)}</h1></div><div class="admin-row-actions"><button data-reset>${t('Reset password','إعادة تعيين كلمة المرور')}</button>${submissions.length?`<a class="client-primary" href="${endpoint('admin_zip',{id})}">${t('Download current · ZIP','تنزيل النسخ الحالية · ZIP')}</a>`:''}</div></div><section class="admin-client-facts"><div><small>${t('Mobile number','رقم الجوال')}</small><strong dir="ltr">${e(user.phone)}</strong></div><div><small>${t('Email','البريد الإلكتروني')}</small><strong dir="ltr">${e(user.email||'—')}</strong></div><div><small>${t('Registered','تاريخ التسجيل')}</small><strong>${e(when(user.created_at,lang))}</strong></div><div><small>${t('Last sign-in','آخر دخول')}</small><strong>${e(when(user.last_login,lang))}</strong></div><div><small>${t('Current forms / archived versions','نماذج حالية / نسخ مؤرشفة')}</small><strong>${current.length} / ${archived.length}</strong></div></section><section class="admin-card"><div class="admin-section-heading"><h2>${t('Current documents','المستندات الحالية')}</h2></div>${table(current,{showClient:false})}</section>${archived.length?`<details class="admin-card admin-history"><summary>${t('Version history','سجل النسخ')} · ${archived.length} ${t('archived','مؤرشفة')}</summary><p class="client-muted">${t('Restoring creates a new current version. Every previous PDF and its details stay saved.','تنشئ الاستعادة نسخة حالية جديدة. تبقى جميع ملفات PDF السابقة وبياناتها محفوظة.')}</p><a class="client-primary history-download" href="${endpoint('admin_zip',{id,history:1})}">${t('Download all versions · ZIP','تنزيل جميع النسخ · ZIP')}</a>${table(archived,{showClient:false})}</details>`:''}${subtitle()}`);
  bindRows();bind('[data-reset]',()=>reset(user));
 }
 function restore(source){
  if(!source)return;
  const current=clientSubmissions.find(s=>!s.archived_at&&s.doc_id===source.doc_id&&s.audience===source.audience);
  const dialog=document.createElement('dialog');dialog.className='client-reset-dialog';dialog.dir=lang==='ar'?'rtl':'ltr';document.body.append(dialog);let busy=false;
  const requestKey=crypto.randomUUID(),close=()=>{if(!busy){dialog.close();dialog.remove();}};
  dialog.innerHTML=`<h2>${t('Restore archived version?','استعادة النسخة المؤرشفة؟')}</h2><p><b>${e(t(source.title,source.ar))}</b></p><p>${t('Version','النسخة')} ${source.version} · ${e(when(source.created_at,lang))}</p><p>${t('This creates a new current version using this PDF and its original details. The current version will move to the archive. Nothing is deleted.','سينشئ هذا نسخة حالية جديدة من ملف PDF هذا وبياناته الأصلية. ستنتقل النسخة الحالية إلى الأرشيف دون حذف أي نسخة.')}</p><p role="status"></p><div class="admin-row-actions"><button data-close>${t('Cancel','إلغاء')}</button><button class="primary" data-confirm-restore>${t('Restore version','استعادة النسخة')}</button></div>`;
  dialog.querySelector('[data-close]').onclick=close;dialog.addEventListener('cancel',ev=>{ev.preventDefault();close();});dialog.showModal();
  dialog.querySelector('[data-confirm-restore]').onclick=async()=>{
   if(busy)return;busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=true);
   try{await api('admin_restore',{id:source.id,expectedCurrent:current?.id??null,requestKey},{token:token()});busy=false;close();await profile(source.user_id);}
   catch(err){dialog.querySelector('[role=status]').textContent=errorText(err,lang);}
   finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}
  };
 }
 function reset(user){
  const dialog=document.createElement('dialog');dialog.className='client-reset-dialog';document.body.append(dialog);let busy=false;
  const close=()=>{if(!busy){dialog.close();dialog.remove();}};
  dialog.innerHTML=`<h2>${t('Reset client password','إعادة تعيين كلمة مرور العميل')}</h2><p><b>${e(user.name)}</b><br><bdi>${e(user.phone)}</bdi></p><p>${t('Generate a strong temporary password. Existing sessions will end, and the client must choose a new password at their next sign-in.','أنشئ كلمة مرور مؤقتة قوية. ستنتهي الجلسات الحالية وسيُطلب من العميل اختيار كلمة مرور جديدة عند دخوله التالي.')}</p><p role="status"></p><div class="admin-row-actions"><button data-close>${t('Cancel','إلغاء')}</button><button class="primary" data-generate>${t('Generate temporary password','إنشاء كلمة مرور مؤقتة')}</button></div>`;
  dialog.querySelector('[data-close]').onclick=close;dialog.addEventListener('cancel',ev=>{ev.preventDefault();close();});dialog.showModal();
  dialog.querySelector('[data-generate]').onclick=async()=>{if(busy)return;busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=true);try{
   const result=await api('admin_reset',{id:user.id},{token:token()});
   dialog.innerHTML=`<h2>${t('Temporary password ready','كلمة المرور المؤقتة جاهزة')}</h2><p>${e(user.name)} · <bdi>${e(user.phone)}</bdi></p><p>${t('Share it with this client through your usual private contact. It is shown only here.','شاركها مع هذا العميل عبر وسيلة تواصل خاصة. تظهر كلمة المرور هنا فقط.')}</p><output class="temporary-password" dir="ltr">${e(result.temporary_password)}</output><p role="status"></p><div class="admin-row-actions"><button data-copy>${t('Copy password','نسخ كلمة المرور')}</button><button class="primary" data-close>${t('Done','تم')}</button></div>`;
   dialog.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(result.temporary_password);dialog.querySelector('[role=status]').textContent=t('Copied.','تم النسخ.');}catch{dialog.querySelector('[role=status]').textContent=t('Select the password above and copy it.','حدد كلمة المرور أعلاه وانسخها.');}};
   dialog.querySelector('[data-close]').onclick=()=>{close();profile(user.id);};
  }catch(err){dialog.querySelector('[role=status]').textContent=errorText(err,lang);}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}};
 }
 return {overview,users};
}
