import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
page.on('pageerror',e=>console.log('PAGE ERROR:',e.message));
await page.goto('http://127.0.0.1:8184/individuals/');
await page.locator('[data-doc="subscription-form"]').click();
await page.screenshot({path:'tmp/subscription/ui-client.png',fullPage:true});
console.log('INPUTS',await page.locator('input,select').evaluateAll(ns=>ns.map(n=>n.name)));
for(const [name,value] of Object.entries({first_name:'أحمد',second_name:'محمد',family_name:'العلي',nationality:'المملكة العربية السعودية',mobile:'+966551234567'}))await page.locator(`[name="${name}"]`).fill(value);
await page.locator('[name="id_type"]').selectOption('national');await page.locator('[name="id_number"]').fill('1000001234');
await page.locator('#sub-next').click();
for(const [name,value] of Object.entries({short_address:'RABC1234',building:'1234',street:'شارع الملك فهد',additional:'5678',district:'العليا',postal:'12345',city:'الرياض',email:'ahmad.ali@example.com'}))await page.locator(`[name="${name}"]`).fill(value);
await page.locator('#sub-next').click();
await page.locator('[name="subscription_type"][value="new"]').check();await page.locator('[name="payment_method"][value="transfer"]').check();await page.locator('[name="units"]').fill('10');
console.log('TOTAL',await page.locator('[data-computed="total_amount"]').innerText());await page.screenshot({path:'tmp/subscription/ui-amounts.png',fullPage:true});
await page.locator('#sub-next').click();console.log('APPLICANT',await page.locator('[name="applicant_name"]').inputValue());await page.locator('#sub-next').click();
await page.locator('[data-pdf-page="2"]').waitFor();await page.waitForFunction(()=>document.querySelector('[data-pdf-page="2"]').width>400);await page.screenshot({path:'tmp/subscription/ui-review.png',fullPage:true});
const downloadEvent=page.waitForEvent('download');await page.locator('[data-download]').last().click();const download=await downloadEvent;await download.saveAs('tmp/subscription/smoke-filled.pdf');
console.log('download',await download.failure());await browser.close();
