"""Read-only checks of the PDFs generated by management-real-files.mjs."""
import json
from pathlib import Path
import numpy as np
import pypdfium2 as pdfium
import pdfplumber
from pypdf import PdfReader
from PIL import Image, ImageDraw
root=Path('tmp/management-real-files')
records=json.loads((root/'results.json').read_text())
report=[]
for record in records:
 if record.get('importError'):continue
 source=pdfium.PdfDocument('public/pdfs/'+record['file'])
 original=PdfReader('public/pdfs/'+record['file'])
 source_text=pdfplumber.open('public/pdfs/'+record['file'])
 source_pages={}
 for i in range(len(source)):
  source_pages[i]=np.asarray(source[i].render(scale=2).to_pil().convert('RGB')).copy()
 placements=[]
 for field in record['fields']:
  boxes=[o['rect'] for o in field.get('options',[])] if field['type']=='choice' else [field['rect']]
  for box in boxes:
   x,y,w,h=box
   hits=[]
   for c in source_text.pages[field['page']-1].chars:
    if not c.get('text','').strip():continue
    iw=min(x+w-2,c['x1'])-max(x+2,c['x0']);ih=min(y+h-2,c['bottom'])-max(y+2,c['top'])
    if iw>.8 and ih>.8:hits.append(c['text'])
   if hits:placements.append({'field':field['id'],'page':field['page'],'printed_characters':''.join(hits)})
 for sample in record['samples']:
  if not sample.get('output'):continue
  result=pdfium.PdfDocument(root/sample['output']);reader=PdfReader(root/sample['output'])
  assert len(result)==len(source)
  blue_total=overlap_total=images=0;page_checks=[]
  for i in range(len(result)):
   page=result[i];pixels=np.asarray(page.render(scale=2).to_pil().convert('RGB')).copy();old=source_pages[i]
   r,g,b=[pixels[:,:,c].astype(int) for c in range(3)]
   changed=np.abs(pixels.astype(int)-old.astype(int)).max(axis=2)>20
   blue=(r<80)&(g>45)&(g<140)&(b>120)&(b>g+35)&changed
   dark=(old.max(axis=2)-old.min(axis=2)<45)&(old.mean(axis=2)<170)
   overlaps=blue&dark;n=int(overlaps.sum());blue_total+=int(blue.sum());overlap_total+=n
   page_checks.append({'page':i+1,'answer_pixels':int(blue.sum()),'source_ink_intersection_pixels':n})
   if sample['name'] in ['english','arabic'] and (blue.any() or i==0):
    image=Image.fromarray(pixels);image.thumbnail((850,1100));image.save(root/(sample['output'].replace('.pdf',f'-p{i+1}.png')))
   old_obj=original.pages[i]['/Resources'].get('/XObject',{})
   old_obj=old_obj.get_object() if hasattr(old_obj,'get_object') else old_obj
   objects=reader.pages[i]['/Resources'].get('/XObject',{});objects=objects.get_object() if hasattr(objects,'get_object') else objects
   for key in set(objects)-set(old_obj):
    obj=objects[key].get_object()
    if obj.get('/Subtype')!='/Image':continue
    assert '/SMask' in obj,'Opaque overlay added'
    alpha=np.frombuffer(obj['/SMask'].get_data(),dtype=np.uint8).reshape(int(obj['/Height']),int(obj['/Width']))
    assert not any(np.any(edge>2) for edge in [alpha[0],alpha[-1],alpha[:,0],alpha[:,-1]]),'Clipped answer image'
    images+=1
  report.append({'file':sample['output'],'pages':len(result),'answer_images':images,'answer_pixels':blue_total,'source_ink_intersection_pixels':overlap_total,'page_checks':page_checks})
  result.close()
 record['source_text_intersections']=placements
 source.close();source_text.close()
(root/'results.json').write_text(json.dumps(records,ensure_ascii=False,indent=2))
(root/'render-checks.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print(json.dumps({'pdfs':len(report),'answer_images':sum(r['answer_images'] for r in report),'pixel_overlap_files':len([r for r in report if r['source_ink_intersection_pixels']]),'placement_intersections':sum(len(r.get('source_text_intersections',[])) for r in records)},indent=2))
