import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {fixture,digest} from './workflow-harness.mjs';
// Run after npm run build. This audit always snapshots dist into a unique local
// fixture and never accepts a remote URL, hosted credentials, or shared storage.
const f=await fixture(),report={base:f.base,baseline:f.baseline,checks:[],errors:[],screenshots:[]};let browser;
const pass=text=>{report.checks.push(text);console.log('PASS '+text);};
const api=(ctx,action,options)=>f.call(ctx,'portal',action,options);
const workflow=async ctx=>(await api(ctx,'admin_workflow')).workflow;
const review=(ctx,id,status,expectedReview=0)=>api(ctx,'admin_review',{data:{id,status,expectedReview,requestKey:randomUUID(),reason_code:status==='rejected'?'incorrect_data':'',reason_text:status==='signature_required'?'Please sign the complete form.':''}});
const detail=async(ctx,id,admin=false)=>(await api(ctx,admin?'admin_detail':'detail',{params:{id}})).submission;
const track=page=>page.on('pageerror',error=>report.errors.push(error.message));
const shape=row=>({id:row.id,doc_id:row.doc_id,audience:row.audience,version:row.version,created_at:row.created_at,source:row.source,answers:row.answers,profile:row.profile,signatures:row.signatures,review_required:row.review_required,review_history:row.review_history});
const subscriptionValues={first_name:'QA',second_name:'Workflow',family_name:'Individual',company_name:'Workflow QA Company',inc_country:'Saudi Arabia',company_id_type:'cr',company_id_number:'4030123456',auth_name:'QA Workflow Company',nationality:'Saudi Arabia',id_type:'national',id_number:'1000012345',mobile:'+966551111111',short_address:'RABC1234',building:'1234',street:'King Fahd Road',additional:'5678',district:'Al Olaya',postal:'12345',city:'Riyadh',country:'المملكة العربية السعودية',email:'workflow-qa@example.com',units:'10',subscription_type:'new',payment_method:'transfer',applicant_name:'QA Workflow',date:'2026-09-19',signature_mode:'manual'};
async function shot(page,name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'No page overflow: '+name);const target=f.out+'/'+name+'.png';await page.screenshot({path:target,fullPage:true});report.screenshots.push(target);}
async function language(page,lang){if(await page.locator('html').getAttribute('lang')!==lang){await page.locator('.site-header-language').click();await page.locator('html[lang='+lang+']').waitFor();}}
async function management(page,lang='en'){await page.goto(f.base+'/management/');await page.locator('.admin-stats').waitFor();await language(page,lang);}
async function setting(page,enabled){await page.locator('[data-management-view=workflow]').click();await page.locator('#workflow-settings-form').waitFor();await page.locator('#workflow-settings-form [value="'+enabled+'"]').check();const sent=page.waitForRequest(request=>new URL(request.url()).searchParams.get('action')==='admin_workflow_update'&&request.method()==='POST');await page.locator('#workflow-settings-form [type=submit]').click();const payload=(await sent).postDataJSON();await page.locator('[data-workflow-mode="'+(enabled?'review':'tool')+'"]').waitFor();await page.locator('[data-workflow-status]').filter({hasText:/saved|حفظ/}).waitFor();return payload;}
async function editor(page,user,doc,{lang='en',width=1440,signed=false}={}){
 const audience=user.account_type,folder=audience==='corporate'?'companies':'individuals',subscription=doc.startsWith('subscription'),values=subscription?subscriptionValues:{client_name:'QA Tool-mode Saved Name'};
 await page.goto(f.base+'/'+folder+'/?lang='+lang);const image=signed?'data:image/png;base64,'+(await fs.readFile('tests/fixtures/signature.png')).toString('base64'):null;
 await page.evaluate(({user,audience,doc,values,lang,image,subscription})=>{const prefix='itqan.forms.v1.account.'+user.id+'.'+audience+'.';localStorage.setItem(prefix+doc,JSON.stringify({values,step:subscription?3:0,signatures:image?{specimen:image}:{},signatureModes:image?{specimen:'electronic'}:{specimen:'manual'}}));localStorage.setItem(prefix+'preferences',JSON.stringify({lang,active:doc}));},{user,audience,doc,values,lang,image,subscription});
 await page.setViewportSize({width,height:1000});await page.goto(f.base+'/'+folder+'/?lang='+lang);
 if(subscription){await page.locator('#sub-next').click();await page.locator('[data-submit]').waitFor();await page.waitForFunction(()=>document.querySelector('#sub-pages canvas')?.width>100);}else{await page.locator('#review-tab').click();await page.locator('#submit-form').waitFor();await page.waitForFunction(()=>document.querySelector('#pdf-canvas')?.width>100);}
 return page.locator(subscription?'[data-submit]':'#submit-form');
}
async function saveFromEditor(page,button){await button.click();await page.locator('.submission-dialog [data-confirm]').click();await page.locator('.submitted-mark').waitFor();assert.match(await page.locator('.submission-dialog h2').textContent(),/saved|حفظ/);await page.locator('.submission-dialog [data-close]').click();}
async function assertPdf(ctx,id,expected){const response=await ctx.request.get(f.base+'/api/portal.php?'+new URLSearchParams({action:'pdf',id}));assert.equal(response.status(),200);assert.equal(digest(await response.body()),expected);}
async function zip(ctx,history,name){const response=await ctx.request.get(f.base+'/api/portal.php?action=zip'+(history?'&history=1':''));assert.equal(response.status(),200);const target=f.out+'/'+name+'.zip';await fs.writeFile(target,await response.body());const parsed=spawnSync('php',['-r','$z=new ZipArchive();$z->open($argv[1]);$r=[];for($i=0;$i<$z->numFiles;$i++)$r[]=hash("sha256",$z->getFromIndex($i));echo json_encode($r);',target],{encoding:'utf8'});assert.equal(parsed.status,0);return JSON.parse(parsed.stdout).sort();}
try{
 browser=await chromium.launch({channel:'chrome',headless:true});const make=()=>browser.newContext({viewport:{width:1440,height:1000}});
 const anon=await make(),admin=await make(),owner=await make(),staleOwner=await make(),individual=await make(),corporate=await make();await f.login(admin,'admin');await f.login(owner,'superadmin');await f.login(staleOwner,'superadmin');
 const publicSession=await api(anon,'session');assert.deepEqual(Object.keys(publicSession.workflow).sort(),['review_enabled','revision']);assert.equal(publicSession.workflow.review_enabled,true);const initial=await workflow(owner);assert.equal(initial.review_enabled,true);
 const u=await f.client(individual,'individual'),company=await f.client(corporate,'corporate');
 const old=await f.submit(individual,u); // A never-switched review site accepts legacy clients without a mode revision.
await review(admin,old.id,'approved');const pending=await f.submit(individual,u,{workflowRevision:initial.revision,expectedCurrent:old.id,editedFrom:old.id});
 const approved=await f.submit(corporate,company,{workflowRevision:initial.revision});await review(admin,approved.id,'approved');
 const unsigned=await f.submit(individual,u,{workflowRevision:initial.revision,expectedCurrent:pending.id,signatures:{},signatureModes:{specimen:'manual'},status:422});assert.equal(unsigned.error,'signature_required');
 const requested=await f.submit(individual,u,{document:'kyc-individual',values:{name_1:u.name},source:'upload',workflowRevision:initial.revision});await review(admin,requested.id,'signature_required');
 const immutable=new Map();for(const [ctx,id] of [[individual,old.id],[individual,pending.id],[individual,requested.id],[corporate,approved.id]]){const d=await detail(owner,id,true);immutable.set(id,{ctx,value:shape(d),sha:d.sha256});}
 const notificationsBefore=await api(individual,'notifications');const baselineStats=(await api(admin,'admin_dashboard')).stats;
 pass('Default review-on, public metadata safety, legacy-client compatibility, signed submissions, signature enforcement and current/archive fixtures');

 const change={review_enabled:false,expectedRevision:initial.revision,requestKey:randomUUID()};
 await api(anon,'admin_workflow_update',{data:change,status:401});await api(individual,'admin_workflow_update',{data:change,status:401});await api(admin,'admin_workflow_update',{data:{...change,role:'superadmin'},status:403});
 await api(owner,'admin_workflow_update',{data:change,status:403,headers:{'X-CSRF-Token':'bad'}});await api(owner,'admin_workflow_update',{data:change,status:403,headers:{'X-CSRF-Token':''}});await api(owner,'admin_workflow_update',{method:'get',status:405});
 for(const invalid of [{review_enabled:'false'},{review_enabled:null},{expectedRevision:'0'},{expectedRevision:-1}])await api(owner,'admin_workflow_update',{data:{...change,...invalid},status:400});
 assert.equal((await workflow(owner)).revision,initial.revision);
 pass('Anonymous, client, regular admin, CSRF, wrong method and invalid workflow updates cannot change mode');

 const op=await owner.newPage(),ap=await admin.newPage(),sp=await staleOwner.newPage(),staleSubmit=await individual.newPage();[op,ap,sp,staleSubmit].forEach(track);await management(op);await management(ap);await management(sp);await sp.locator('[data-management-view=workflow]').click();assert.equal(await ap.locator('[data-management-view=workflow]').count(),0);
 await ap.locator('[data-management-view=reviews]').click();await ap.locator('[data-preview="'+pending.id+'"]').click();await ap.locator('.review-form [name=status]').selectOption('approved');
 const beforeSubmit=await editor(staleSubmit,u,'signature-form',{signed:true});await beforeSubmit.click();await staleSubmit.locator('.submission-dialog [data-confirm]').waitFor();
 const offPayload=await setting(op,false);const off=await workflow(owner);assert.equal(off.review_enabled,false);assert.equal(off.revision,initial.revision+1);
 assert.equal((await api(owner,'admin_workflow_update',{data:offPayload})).duplicate,true);assert.equal((await api(owner,'admin_workflow')).history.length,1);
 assert.equal((await api(owner,'admin_workflow_update',{data:{review_enabled:false,expectedRevision:off.revision,requestKey:randomUUID()},status:409})).error,'workflow_unchanged');
 await sp.locator('#workflow-settings-form [value=false]').check();const conflictingResponse=sp.waitForResponse(response=>new URL(response.url()).searchParams.get('action')==='admin_workflow_update');await sp.locator('#workflow-settings-form [type=submit]').click();assert.equal((await conflictingResponse).status(),409);await sp.locator('[data-workflow-status]').filter({hasText:/changed|تغي/}).waitFor();assert.equal(await sp.locator('#workflow-settings-form [value=false]').isChecked(),true);await sp.close();
 await api(staleOwner,'admin_workflow_update',{data:{review_enabled:true,expectedRevision:initial.revision,requestKey:randomUUID()},status:409});assert.equal((await workflow(owner)).review_enabled,false);
 await f.stop();await f.start();const publicOff=(await api(anon,'session')).workflow;assert.equal(publicOff.review_enabled,false);assert.deepEqual(Object.keys(publicOff).sort(),['review_enabled','revision']);assert.equal((await workflow(owner)).revision,off.revision);
 await ap.locator('.review-form [type=submit]').click();await ap.locator('.review-form').waitFor({state:'detached'});
 await staleSubmit.locator('.submission-dialog [data-confirm]').click();await staleSubmit.locator('.submission-dialog [data-message].error').waitFor();assert.equal((await api(admin,'admin_dashboard')).stats.submissions,baselineStats.submissions);
 for(const status of ['approved','rejected','signature_required'])assert.equal((await api(admin,'admin_review',{data:{id:pending.id,status,expectedReview:0,requestKey:randomUUID(),reason_code:status==='rejected'?'incorrect_data':'',reason_text:''},status:409})).error,'workflow_disabled');
 assert.equal((await api(admin,'admin_review_queue',{status:409})).error,'workflow_disabled');
 for(const source of ['online','upload'])assert.equal((await f.submit(individual,u,{source,workflowRevision:initial.revision,expectedCurrent:pending.id,status:409})).error,'workflow_conflict');
 const signMetadata={account:u.id,sourceId:requested.id,sourceSha256:immutable.get(requested.id).sha,expectedCurrent:requested.id,requestKey:randomUUID(),workflowRevision:initial.revision,signatures:{client:'data:image/png;base64,'+(await fs.readFile('tests/fixtures/signature.png')).toString('base64')}};assert.equal((await api(individual,'sign_submission',{multipart:{metadata:JSON.stringify(signMetadata),pdf:{name:'qa-stale-signing.pdf',mimeType:'application/pdf',buffer:await fs.readFile(f.out+'/site/pdfs/kyc-individual.pdf')}},status:409})).error,'workflow_conflict');
 assert.equal((await f.submit(individual,u,{expectedCurrent:pending.id,status:409})).error,'workflow_conflict');
 assert.deepEqual((await detail(admin,pending.id,true)).review_history,[]);assert.deepEqual((await api(individual,'notifications')).notifications,notificationsBefore.notifications);
 const restoredWhileOff=(await api(owner,'admin_restore',{data:{id:old.id,expectedCurrent:pending.id,requestKey:randomUUID()},status:201})).submission;assert.equal(restoredWhileOff.review_required,true);assert.equal((await detail(admin,restoredWhileOff.id,true)).workflow_enabled,false);assert.deepEqual((await detail(admin,restoredWhileOff.id,true)).review_history,[]);
 pass('Actual superadmin off save persists across restart; optimistic conflict, stale decision and stale save are blocked without new versions, decisions or notifications');

 await staleSubmit.close();const ip=await individual.newPage(),cp=await corporate.newPage();[ip,cp].forEach(track);
 let toolGeneric,toolIndividual,toolCompany;
 for(const lang of ['en','ar'])for(const width of [1440,390]){
  await op.setViewportSize({width,height:1000});await management(op,lang);assert.equal(await op.locator('[data-management-view=reviews]').count(),0);assert.equal(await op.locator('#management-notifications').count(),0);await op.locator('[data-management-view=workflow]').click();assert.equal(await op.locator('[name=review_enabled][value=false]').isChecked(),true);await shot(op,'workflow-off-'+lang+'-'+width);
  await ap.setViewportSize({width,height:1000});await management(ap,lang);assert.equal(await ap.locator('[data-management-view=reviews],[data-management-view=workflow],#management-notifications').count(),0);await shot(ap,'admin-off-'+lang+'-'+width);
  for(const [page,user,doc] of [[ip,u,'signature-form'],[ip,u,'subscription-form'],[cp,company,'subscription-company']]){
   const button=await editor(page,user,doc,{lang,width});assert.equal(await button.isDisabled(),false);assert.match(await button.textContent(),/Save|حفظ/);assert.equal(await page.locator('.submission-signing-note').count(),0);await shot(page,'tool-'+doc+'-'+lang+'-'+width);
   if(lang==='en'&&width===1440){const download=page.waitForEvent('download');await page.locator(doc.startsWith('subscription')?'[data-download]':'#download').last().click();await(await download).saveAs(f.out+'/tool-'+doc+'.pdf');assert.equal(await page.locator('.signing-guide').count(),0);await saveFromEditor(page,button);const rows=(await api(user===u?individual:corporate,'submissions')).submissions,saved=rows.find(s=>s.doc_id===doc&&!s.archived_at);assert.equal(saved.review_required,false);assert.equal(saved.workflow_enabled,false);if(doc==='signature-form')toolGeneric=saved;else if(doc==='subscription-form')toolIndividual=saved;else toolCompany=saved;}
  }
  for(const [page,ctx] of [[ip,individual],[cp,corporate]]){await page.goto(f.base+'/my-applications/?lang='+lang);await page.locator('.account-documents').waitFor();assert.equal(await page.locator('.client-submission .review-pending,.client-submission .review-signature_required,.client-submission .review-approved,.client-signature-remedy').count(),0);for(const label of await page.locator('[data-sign]').allTextContents())assert.match(label,/optional|اختياري/);await shot(page,'tool-account-'+(ctx===individual?'individual':'corporate')+'-'+lang+'-'+width);}
 }
 for(const [ctx,row] of [[individual,toolGeneric],[individual,toolIndividual],[corporate,toolCompany]]){const d=await detail(ctx,row.id);assert.equal(d.profile.review_required,false);assert.equal(d.review_required,false);assert.equal(d.signature_state,'unsigned');assert.deepEqual(d.review_history,[]);}
 assert.equal((await detail(individual,toolIndividual.id)).answers.total_amount,'10200');assert.equal((await detail(corporate,toolCompany.id)).answers.total_amount,'10200');
 await ip.goto(f.base+'/my-applications/?lang=en');await ip.locator('#upload-completed').click();await ip.locator('.portal-upload').waitFor();assert.equal(await ip.locator('.portal-upload [name=signedConfirmed]').count(),0);await ip.locator('.portal-upload [name=document]').selectOption('al-naeem-terms-consent');await ip.locator('.portal-upload [name=pdf]').setInputFiles(f.out+'/site/pdfs/al-naeem-terms-consent.pdf');await ip.locator('.portal-upload .primary').click();await ip.locator('.portal-upload').waitFor({state:'detached'});const uploadedOff=(await api(individual,'submissions')).submissions.find(s=>s.doc_id==='al-naeem-terms-consent'&&!s.archived_at);assert.ok(uploadedOff);assert.equal(uploadedOff.review_required,false);assert.equal((await detail(individual,uploadedOff.id)).profile.signed_confirmed,false);
 pass('EN/AR desktop/mobile tool UI saves actual unsigned generic and both subscription PDFs with correct totals; saved account views have no active review remedies');

 const partialSource=await f.submit(corporate,company,{document:'fatca-crs-corporate',source:'upload',signedConfirmed:false,workflowRevision:off.revision}),partialSourceDetail=await detail(corporate,partialSource.id),beforePartialCount=(await api(corporate,'submissions')).submissions.length;
 const partialMeta={account:company.id,sourceId:partialSource.id,sourceSha256:partialSourceDetail.sha256,expectedCurrent:partialSource.id,requestKey:randomUUID(),workflowRevision:off.revision,signatures:{}};
 assert.equal((await api(corporate,'sign_submission',{multipart:{metadata:JSON.stringify(partialMeta),pdf:{name:'qa-no-signature.pdf',mimeType:'application/pdf',buffer:await fs.readFile(f.out+'/site/pdfs/fatca-crs-corporate.pdf')}},status:422})).error,'signature_image_required');assert.equal((await api(corporate,'submissions')).submissions.length,beforePartialCount);
 await cp.goto(f.base+'/my-applications/?lang=ar');await cp.locator('.account-documents').waitFor();assert.equal(await cp.locator('button[data-sign="'+partialSource.id+'"]').count(),1,'Unknown-signature uploads offer optional signing in tool mode');await cp.locator('[data-preview="'+partialSource.id+'"]').click();await cp.locator('.portal-preview [data-sign-submission]').click();await cp.locator('.portal-signing [data-sign-file=signatory_1]:not([disabled])').waitFor();assert.equal(await cp.locator('[data-sign-preview]').isDisabled(),true);await cp.locator('[data-sign-file=signatory_1]').setInputFiles('tests/fixtures/signature.png');await cp.locator('[data-slot=signatory_1] [data-sign-image] img').waitFor();await cp.locator('[data-sign-preview]').click();await cp.locator('.portal-signing [name=reviewed]').check();await cp.locator('[data-sign-submit]:enabled').waitFor();await shot(cp,'tool-optional-partial-signature-ar-mobile');await cp.locator('[data-sign-submit]').click();await cp.locator('.portal-signing').waitFor({state:'detached'});
 const partialSaved=(await api(corporate,'submissions')).submissions.find(s=>s.doc_id==='fatca-crs-corporate'&&!s.archived_at),partialDetail=await detail(corporate,partialSaved.id);assert.equal(partialSaved.review_required,false);assert.deepEqual(Object.keys(partialDetail.signatures),['signatory_1']);assert.notEqual(partialDetail.sha256,partialSourceDetail.sha256);await assertPdf(corporate,partialSource.id,partialSourceDetail.sha256);assert.ok((await detail(corporate,partialSource.id)).archived_at);
 pass('Optional signing rejects an empty request without mutation; actual Arabic mobile upload previews/saves one optional signature while the normally required slot stays blank');

 for(const [id,{ctx,value,sha}] of immutable){assert.deepEqual(shape(await detail(admin,id,true)),value);await assertPdf(ctx,id,sha);}
 for(const [ctx,name] of [[individual,'individual'],[corporate,'corporate']]){const rows=(await api(ctx,'submissions')).submissions;assert.deepEqual(await zip(ctx,false,name+'-current'),rows.filter(s=>!s.archived_at).map(s=>s.sha256).sort());assert.deepEqual(await zip(ctx,true,name+'-history'),rows.map(s=>s.sha256).sort());}
 await api(corporate,'detail',{params:{id:toolGeneric.id},status:404});await api(individual,'detail',{params:{id:toolCompany.id},status:404});
 await ip.goto(f.base+'/individuals/?submission='+old.id+'&lang=ar');await ip.locator('#f-client_name').waitFor();assert.equal(await ip.locator('#f-client_name').inputValue(),u.name);
 await op.goto(f.base+'/management/');await op.locator('[data-management-view=users]').click();await op.locator('#client-search').waitFor();await op.locator('[data-client="'+u.id+'"]').click();await op.locator('.admin-history summary').click();await op.locator('[data-preview="'+old.id+'"]').click();await op.locator('.portal-pdf-pages canvas').first().waitFor();assert.equal(await op.locator('.review-form').count(),0);assert.equal(await op.locator('.review-history li').count(),1);await op.locator('[data-current-version]').click();await op.locator('.portal-pdf-pages canvas').first().waitFor();assert.equal(await op.locator('.review-form').count(),0);await op.locator('.portal-preview [data-close]').click();
 pass('Old/current links, read-only decision history, ownership, current/history ZIP exact hashes and original PDF/answers survive tool mode');

 await management(op);await setting(op,true);const on=await workflow(owner);assert.equal(on.review_enabled,true);assert.equal(on.revision,off.revision+1);
 const settings=await api(owner,'admin_workflow');assert.ok(settings.history.length>=2);assert.equal(settings.workflow.updated_by,f.credentials.superadmin.username);assert.match(settings.workflow.updated_at,/^20\d\d-/);assert.ok(settings.history.some(r=>r.review_enabled===false));assert.ok(settings.history.some(r=>r.review_enabled===true));
 for(const lang of ['en','ar'])for(const width of [1440,390]){await op.setViewportSize({width,height:1000});await management(op,lang);await op.locator('[data-management-view=workflow]').click();assert.equal(await op.locator('[name=review_enabled][value=true]').isChecked(),true);assert.equal(await op.locator('.workflow-history li').count(),2);await shot(op,'workflow-on-'+lang+'-'+width);}
 assert.deepEqual((await api(individual,'notifications')).notifications,notificationsBefore.notifications);
 const queue=await api(admin,'admin_review_queue',{params:{status:'all'}});for(const row of [toolGeneric,toolIndividual,toolCompany,uploadedOff,partialSaved]){assert.equal(queue.submissions.some(s=>s.id===row.id),false);const d=await detail(admin,row.id,true);assert.equal(d.review_required,false);assert.equal(d.workflow_enabled,true);const rejected=await api(admin,'admin_review',{data:{id:row.id,status:'approved',expectedReview:0,requestKey:randomUUID(),reason_code:'',reason_text:''},status:409});assert.equal(rejected.error,'workflow_not_required');}
 const approvedRevision=(await detail(admin,approved.id,true)).review_revision;for(const status of ['rejected','signature_required'])assert.equal((await api(admin,'admin_review',{data:{id:approved.id,status,reason_code:status==='rejected'?'incorrect_data':'',reason_text:'',expectedReview:approvedRevision,requestKey:randomUUID()},status:409})).error,'review_locked');
 for(const [id,{value}] of immutable)assert.deepEqual(shape(await detail(admin,id,true)),value);
 await op.locator('[data-management-view=reviews]').click();await op.locator('[data-review-status=approved]').click();await op.locator('[data-preview="'+approved.id+'"]').click();await op.locator('.review-form').waitFor();assert.equal(await op.locator('.review-form [name=status]').isDisabled(),true);await op.locator('.portal-preview [data-close]').click();
 await ip.goto(f.base+'/my-applications/?lang=en');await ip.locator('.account-documents').waitFor();assert.equal(await ip.locator('[data-review-id="'+toolGeneric.id+'"] .review-saved').count(),1);assert.equal(await ip.locator('[data-review-id="'+requested.id+'"] .review-signature_required').count(),1);
 assert.equal((await f.submit(individual,u,{workflowRevision:off.revision,expectedCurrent:toolGeneric.id,signatures:{},signatureModes:{specimen:'manual'},status:409})).error,'workflow_conflict');
 assert.equal((await f.submit(individual,u,{workflowRevision:on.revision,expectedCurrent:toolGeneric.id,signatures:{},signatureModes:{specimen:'manual'},status:422})).error,'signature_required');
 for(const [ctx,user,document,current] of [[individual,u,'subscription-form',toolIndividual],[corporate,company,'subscription-company',toolCompany]])assert.equal((await f.submit(ctx,user,{document,values:subscriptionValues,workflowRevision:on.revision,expectedCurrent:current.id,signatures:{},signatureModes:{applicant:'manual'},status:422})).error,'signature_required');
 const fresh=await f.submit(individual,u,{workflowRevision:on.revision,expectedCurrent:toolGeneric.id,editedFrom:toolGeneric.id});assert.equal(fresh.review_required,true);await review(admin,fresh.id,'approved');
 const restoredTool=(await api(owner,'admin_restore',{data:{id:toolGeneric.id,expectedCurrent:fresh.id,requestKey:randomUUID()},status:201})).submission;assert.equal(restoredTool.review_required,false);assert.deepEqual((await detail(admin,restoredTool.id,true)).review_history,[]);
 assert.equal((await api(admin,'admin_review_queue',{params:{status:'all'}})).submissions.some(s=>s.id===restoredTool.id),false);
 const restoredEligible=(await api(owner,'admin_restore',{data:{id:old.id,expectedCurrent:restoredTool.id,requestKey:randomUUID()},status:201})).submission;assert.equal(restoredEligible.review_required,true);const restoredDetail=await detail(admin,restoredEligible.id,true);assert.equal(restoredDetail.review_status,'pending');assert.deepEqual(restoredDetail.review_history,[]);assert.equal((await api(admin,'admin_review_queue',{params:{status:'pending'}})).submissions.some(s=>s.id===restoredEligible.id),true);assert.deepEqual(shape(await detail(admin,old.id,true)),immutable.get(old.id).value);
 pass('Re-enable preserves decisions and locked approval, never enrolls tool-mode versions, rejects stale mode/unsigned review submissions, and keeps restored tool versions ineligible');
 assert.deepEqual(report.errors,[]);report.coverage={browser:'Chrome',languages:['en','ar'],widths:[1440,390],groups:report.checks.length,screenshots:report.screenshots.length,syntheticAccounts:2};report.limits=['Local production-build snapshot only; no production requests or mode changes.','Chromium browser coverage; no Firefox/WebKit matrix in this targeted workflow suite.','PDF downloads and ZIP hashes are checked; full official source/layout fidelity is covered by separate PDF audits.'];report.passed=true;console.log('PASS Workflow cycle '+f.out+'/report.json');
}catch(error){report.passed=false;report.failure=error.stack;console.error(error);process.exitCode=1;}
finally{await fs.writeFile(f.out+'/report.json',JSON.stringify(report,null,2));await browser?.close();await f.close();}
